node:
  # image_topic: '/camera/color/image_raw'
  image_topic: /torobo/head/sr300/camera/color/image_raw
  object_position_topic: '/foundationpose/position'
  lifting_direction_topic: '/force_estimation/lifting_direction'
model:
  check_point_dir: '../runs/20241017_0052_35'
  weight_file: '08000.pth'
forcemap:
  name: 'small_table'
preprocess:
  # roi_size: [1280, 720]
  # roi_center: [-40, 75]  # [x, y]
  roi_center: [0, 0]  # [x, y]
  # side_crop: 64
lifting_planning:
  object_radius: 0.05  # [m]
debug:
  save_result: False
